### ISSUE TITLE
SQL command not working

### ISSUE THREAD

**Issue by gagantous** [abedputra/GoInstaller#1]
I have changed my `install\assets\sqlcommand.sql` with my sql query, but it's not working, the sql didnt imported

**Comment by abedputra** [comment]
Hi,
Can you send the SQL commands?

**Comment by gagantous** [comment]
Here 
[install.zip](https://github.com/abedputra/GoInstaller/files/1590342/install.zip)

**Comment by abedputra** [comment]
May I know whats error message?

**Comment by gagantous** [comment]
there is no error message, the sql just not imported to my mysql database, it just make the db, but not the table and its content

**Comment by gagantous** [comment]
could you fix this bugs ?

**Comment by abedputra** [comment]
Not yet.
I will try to fix it.

**Comment by abedputra** [comment]
I find the problem.
you have 45 table, so MYSQL need a time to add all your database, so you need to wait, and it will do on background process.
Please see my attachment, I am success add your database, but I need to wait because add 45 table.

<img width="686" alt="screen shot 2018-01-02 at 10 09 15" src="https://user-images.githubusercontent.com/11581453/34472814-12c8cb3a-efa5-11e7-9529-5b462524586f.png">
